In [ ]:
import os

In [ ]:
base_dir= '/home/t-dimaha/RobustDG/robustdg/amlt/'
list_dir= ['mdg_htune_photo', 'mdg_htune_art_painting', 'mdg_htune_cartoon',  'mdg_htune_sketch']
list_model= ['alexnet', 'resnet18', 'resnet50']

for model_name in list_model:
    for dir_name in list_dir:
            
        count=0
        res={}
        curr_dir = base_dir + dir_name
        for case in ['source', 'target']:
            res[case]={}
            for metric in ['acc', 'std']:
                res[case][metric]= 0.0

        for subdir, dirs, files in os.walk(curr_dir):
            
            if model_name not in subdir:
                continue
                
            if 'weigh_0.0005' not in subdir:
                continue
                
#             if 'lr_0.01' not in subdir:
#                 continue
            
#             # To only obtain ERM results
#             if '_penal_0_' in subdir:
#                 continue
            
            for file in files:
                if 'stdout' in file :
                    f=open(os.path.join(subdir, file), 'r')
                    data= f.readlines()

                    for idx in range(-40, -30):
                        if 'Source' in data[idx] and 'Final' in data[idx]:
                            case = 'source'
                            mean= float(data[idx].split(')')[-1][1:].split(' ')[0])
                            std= float(data[idx].split(')')[-1][1:].split(' ')[1].rstrip('\n'))
                            count+=1
                            if mean > res[case]['acc'] or ( mean == res[case]['acc'] and std < res[case]['std'] ): 
                                res[case]['acc']= mean
                                res[case]['std']= std
                                res[case]['name']= os.path.join(subdir, file)                    
                                
                        elif 'Target' in data[idx] and 'Final' in data[idx] :
                            case = 'target'
                            mean= float(data[idx].split(')')[-1][1:].split(' ')[0])
                            std= float(data[idx].split(')')[-1][1:].split(' ')[1].rstrip('\n'))
                            count+=1
                            if mean > res[case]['acc'] or ( mean == res[case]['acc'] and std < res[case]['std'] ): 
                                res[case]['acc']= mean
                                res[case]['std']= std
                                res[case]['name']= os.path.join(subdir, file)                    
                                
            
            
        print(model_name, dir_name)
        print(count/2)
        print(res)
        print('\n')

In [ ]:
base_dir= '/home/t-dimaha/RobustDG/robustdg/amlt/'
list_dir= ['rand_htune_photo', 'rand_htune_art_painting', 'rand_htune_cartoon', 'rand_htune_sketch', 'mdghyb_htune_sketch']
list_model= ['resnet18', 'resnet50']

for model_name in list_model:
    for dir_name in list_dir:
            
        count=0
        res={}
        curr_dir = base_dir + dir_name
        for case in ['source', 'target']:
            res[case]={}
            for metric in ['acc', 'std']:
                res[case][metric]= 0.0

        for subdir, dirs, files in os.walk(curr_dir):
            
            if model_name not in subdir:
                continue
                
#             if 'weigh' not in subdir:
#                 continue
                
#             if 'lr_0.01' not in subdir:
#                 continue
            
#             # To only obtain ERM results
#             if '_penal_0_' in subdir:
#                 continue
            
            for file in files:
                if 'stdout' in file :
                    f=open(os.path.join(subdir, file), 'r')
                    data= f.readlines()
                    
                    for idx in range(-40, -30):
                        if 'Source' in data[idx] and 'Final' in data[idx]:
                            case = 'source'
                            mean= float(data[idx].split(')')[-1][1:].split(' ')[0])
                            std= float(data[idx].split(')')[-1][1:].split(' ')[1].rstrip('\n'))
                            count+=1
                            if mean > res[case]['acc'] or ( mean == res[case]['acc'] and std < res[case]['std'] ): 
                                res[case]['acc']= mean
                                res[case]['std']= std
                                res[case]['name']= os.path.join(subdir, file)                    
                                
                        elif 'Target' in data[idx] and 'Final' in data[idx]:
                            case = 'target'
                            mean= float(data[idx].split(')')[-1][1:].split(' ')[0])
                            std= float(data[idx].split(')')[-1][1:].split(' ')[1].rstrip('\n'))
                            count+=1
                            if mean > res[case]['acc'] or ( mean == res[case]['acc'] and std < res[case]['std'] ): 
                                res[case]['acc']= mean
                                res[case]['std']= std
                                res[case]['name']= os.path.join(subdir, file)                    
            
            
        print(model_name, dir_name)
        print(count/2)
        print(res)
        print('\n')

In [ ]:
base_dir= '/home/t-dimaha/RobustDG/robustdg/amlt/'
list_dir= ['erm_htune_photo', 'erm_htune_art_painting', 'erm_htune_cartoon', 'erm_htune_sketch']
list_model= ['alexnet', 'resnet18']

for model_name in list_model:
    for dir_name in list_dir:
            
        count=0
        res={}
        curr_dir = base_dir + dir_name
        for case in ['source', 'target']:
            res[case]={}
            for metric in ['acc', 'std']:
                res[case][metric]= 0.0

        for subdir, dirs, files in os.walk(curr_dir):
            
            if model_name not in subdir:
                continue
                
#             if 'weigh' not in subdir:
#                 continue
                
#             if 'lr_0.01' not in subdir:
#                 continue
            
#             # To only obtain ERM results
#             if '_penal_0_' in subdir:
#                 continue
            
            for file in files:
                if 'stdout' in file :
                    f=open(os.path.join(subdir, file), 'r')
                    data= f.readlines()
                    
                    for idx in range(-40, -30):
                        if 'Source' in data[idx] and 'Final' in data[idx]:
                            case = 'source'
                            mean= float(data[idx].split(')')[-1][1:].split(' ')[0])
                            std= float(data[idx].split(')')[-1][1:].split(' ')[1].rstrip('\n'))
                            count+=1
                            if mean > res[case]['acc'] or ( mean == res[case]['acc'] and std < res[case]['std'] ): 
                                res[case]['acc']= mean
                                res[case]['std']= std
                                res[case]['name']= os.path.join(subdir, file)                    
                                
                        elif 'Target' in data[idx] and 'Final' in data[idx]:
                            case = 'target'
                            mean= float(data[idx].split(')')[-1][1:].split(' ')[0])
                            std= float(data[idx].split(')')[-1][1:].split(' ')[1].rstrip('\n'))
                            count+=1
                            if mean > res[case]['acc'] or ( mean == res[case]['acc'] and std < res[case]['std'] ): 
                                res[case]['acc']= mean
                                res[case]['std']= std
                                res[case]['name']= os.path.join(subdir, file)                    
            
            
        print(model_name, dir_name)
        print(count/2)
        print(res)
        print('\n')

In [ ]:
base_dir= '/home/t-dimaha/RobustDG/robustdg/amlt/'
list_dir= ['hyb_htune_photo', 'hyb_htune_art_painting', 'hyb_htune_cartoon', 'hyb_htune_sketch']
list_model= ['alexnet']

for model_name in list_model:
    for dir_name in list_dir:
            
        count=0
        res={}
        curr_dir = base_dir + dir_name
        for case in ['source', 'target']:
            res[case]={}
            for metric in ['acc', 'std']:
                res[case][metric]= 0.0

        for subdir, dirs, files in os.walk(curr_dir):
            
            if model_name not in subdir:
                continue
                
#             if 'weigh' not in subdir:
#                 continue
                
#             if 'lr_0.01' not in subdir:
#                 continue
            
#             # To only obtain ERM results
#             if '_penal_0_' in subdir:
#                 continue
            
            for file in files:
                if 'stdout' in file :
                    f=open(os.path.join(subdir, file), 'r')
                    data= f.readlines()
                    
                    for idx in range(-40, -30):
                        if 'Source' in data[idx] and 'Final' in data[idx]:
                            case = 'source'
                            mean= float(data[idx].split(')')[-1][1:].split(' ')[0])
                            std= float(data[idx].split(')')[-1][1:].split(' ')[1].rstrip('\n'))
                            count+=1
                            if mean > res[case]['acc'] or ( mean == res[case]['acc'] and std < res[case]['std'] ): 
                                res[case]['acc']= mean
                                res[case]['std']= std
                                res[case]['name']= os.path.join(subdir, file)                    
                                
                        elif 'Target' in data[idx] and 'Final' in data[idx]:
                            case = 'target'
                            mean= float(data[idx].split(')')[-1][1:].split(' ')[0])
                            std= float(data[idx].split(')')[-1][1:].split(' ')[1].rstrip('\n'))
                            count+=1
                            if mean > res[case]['acc'] or ( mean == res[case]['acc'] and std < res[case]['std'] ): 
                                res[case]['acc']= mean
                                res[case]['std']= std
                                res[case]['name']= os.path.join(subdir, file)                    
            
            
        print(model_name, dir_name)
        print(count/2)
        print(res)
        print('\n')

In [ ]:
base_dir= '/home/t-dimaha/RobustDG/robustdg/pt/'
list_dir= ['irm_mnist/', 'irm_fmnist/']

for dir_name in list_dir:

    count=0
    res={}
    curr_dir = base_dir + dir_name
    for case in ['source', 'target']:
        res[case]={}
        for metric in ['acc', 'std', 'name']:
            res[case][metric]= 0.0

    for subdir, dirs, files in os.walk(curr_dir):

        for file in files:
            if 'stdout' in file :
                f=open(os.path.join(subdir, file), 'r')
                data= f.readlines()

                for case in ['source', 'target']:
                    if case == 'source':
                        idx=-5
                    else:
                        idx=-4

                    if 'Final' in data[idx]:
                        mean= float(data[idx].split(')')[-1][1:].split(' ')[0])
                        std= float(data[idx].split(')')[-1][1:].split(' ')[1].rstrip('\n'))
                        count+=1

                        if mean > res[case]['acc'] or ( mean == res[case]['acc'] and std < res[case]['std'] ): 
                            res[case]['acc']= mean
                            res[case]['std']= std
                            res[case]['name']= os.path.join(subdir, file)
    print( dir_name)
    print(count/2)
    print(res)
    print('\n')

# IRM Loss Plot

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(10,4))
fig.suptitle('Example of a Single Legend Shared Across Multiple Subplots')

# The data
x =  [1, 2, 3]
y1 = [1, 2, 3]
y2 = [3, 1, 3]
y3 = [1, 3, 1]
y4 = [2, 2, 3]

# Labels to use in the legend for each line
line_labels = ["Line A", "Line B", "Line C", "Line D"]

# Create the sub-plots, assigning a different color for each line.
# Also store the line objects created
l1 = ax1.plot(x, y1, color="red")[0]
ax1.set_title('Blah')
ax1.set_xlabel('No')
l2 = ax2.plot(x, y2, color="green")[0]
l3 = ax3.plot(x, y3, color="blue")[0]
l4 = ax3.plot(x, y4, color="orange")[0] # A second line in the third subplot

# Create the legend
fig.legend([l1, l2, l3, l4],     # The line objects
           labels=line_labels,   # The labels for each line
           loc="center right",   # Position of legend
           borderaxespad=0.1,    # Small spacing around legend box
           title="Legend Title"  # Title for the legend
           )

# Adjust the scaling factor to fit your legend text completely outside the plot
# (smaller value results in more space being made for the legend)
plt.subplots_adjust(right=0.85)

plt.show()

In [ ]:
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13,5))
fontsize=22
ax1.tick_params(labelsize=20)
ax2.tick_params(labelsize=20)

base_dir='results/rot_mnist/plots/'
legend_arr_mnist=[]
for case in ['ERM', 'IRM']:    
    if case == 'IRM':    
        file= base_dir + 'irm_1_5.txt'
    elif case == 'ERM':
        file= base_dir + 'irm_0_-1.txt'
    
    count=0
    y=[]
    f=open(file ,'r')
    data= f.readlines()
    for line in data:
        if 'Train Loss Basic' in line:
            y.append( float( line.split(':')[-1].split(' ')[-1].rstrip('\n') ) / 625 ) 
            count+=1
            if count == 25:
                break
    
    ax1.plot(range(1, 1+len(y)), y, label=case)
#     print(y)
ax1.set_xlabel('Training Epochs', fontsize=fontsize)
ax1.set_ylabel('IRM Loss Penalty', fontsize=fontsize)
ax1.set_title('Rot MNIST', fontsize=fontsize)
ax1.axvline(x=10, ls='--', color='purple', label='ERM: Perfect Train Acc')
ax1.axvline(x=11, ls='--', color='red', label='IRM: Perfect Train Acc')


legend_arr_fmnist=[]
base_dir='results/fashion_mnist/plots/'
for case in ['ERM', 'IRM']:    
    if case == 'IRM':    
        file= base_dir + 'irm_0.05_-1.txt'
    elif case == 'ERM':
        file= base_dir + 'irm_0_-1.txt'
    
    count=0
    y=[]
    f=open(file ,'r')
    data= f.readlines()
    for line in data:
        if 'Train Loss Basic' in line:
            y.append( float( line.split(':')[-1].split(' ')[-1].rstrip('\n') ) / (5*625) ) 
            count+=1
            if count == 25:
                break
    
    ax2.plot(range(1, 1+len(y)), y, label=case)
    
ax2.set_xlabel('Training Epochs', fontsize=fontsize)
# ax2.set_ylabel('IRM Loss Penalty', fontsize=fontsize)
ax2.set_title('Fashion MNIST', fontsize=fontsize)
ax2.axvline(x=19, ls='--', color='purple', label='ERM: Perfect Train Acc')
ax2.axvline(x=21, ls='--', color='red', label='IRM: Perfect Train Acc')

lines, labels = fig.axes[-1].get_legend_handles_labels()    
lgd= fig.legend(lines, labels, loc="lower center", bbox_to_anchor=(0.5, -0.3), fontsize=fontsize, ncol=2)
plt.savefig('results/irm_plot.jpg', bbox_extra_artists=(lgd,), bbox_inches='tight', dpi=300)

In [ ]:
for case in [ 'ERM', 'IRM']:
    if case == 'irm':    
        file= '/home/t-dimaha/RobustDG/robustdg/pt/irm_fmnist/search_irm_fmnist_penal_0.05_thres_-1/stdout.txt'
    if case == 'irm: p1':    
        file= '/home/t-dimaha/RobustDG/robustdg/pt/irm_fmnist/search_irm_fmnist_penal_1_thres_-1/stdout.txt'
    if case == 'irm: p5':    
        file= '/home/t-dimaha/RobustDG/robustdg/pt/irm_fmnist/search_irm_fmnist_penal_5_thres_-1/stdout.txt'
    elif case == 'erm':
        file= '/home/t-dimaha/RobustDG/robustdg/pt/irm_fmnist/search_irm_fmnist_penal_0_thres_-1/stdout.txt'
    
    count=0
    y=[]
    f=open(file ,'r')
    data= f.readlines()
    for line in data:
        if 'Train Loss Basic' in line:
            y.append( float( line.split(':')[-1].split(' ')[-1].rstrip('\n') ) ) 
            count+=1
            if count == 25:
                break
    
    plt.plot(range(1, 1+len(y)), y, label=case)
    print(y)
plt.xlabel('Epochs')
plt.ylabel('IRM Penalty')
plt.title('IRM Penalty during training process')
plt.legend()
plt.show()

## MatchDG Plots

In [ ]:
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13,5))
fontsize=22
ax1.tick_params(labelsize=20)
ax2.tick_params(labelsize=20)

base_dir='results/rot_mnist/plots/'
legend_arr_mnist=[]
for case in ['ERM', 'MatchDG']:    
    if case == 'MatchDG':    
        file= base_dir + 'matchdg.txt'
    elif case == 'ERM':
        file= base_dir + 'erm.txt'
        
    count=0
    y=[]
    f=open(file ,'r')
    data= f.readlines()
    for line in data:
        if 'Train Loss Basic' in line:
            y.append( float( line.split(':')[-1].split(' ')[-1].rstrip('\n') ) / 625 ) 
            count+=1
            if count == 25:
                break
    
    ax1.plot(range(1, 1+len(y)), y, label=case)
#     print(y)
ax1.set_xlabel('Training Epochs', fontsize=fontsize)
ax1.set_ylabel('MatchDG Loss Penalty', fontsize=fontsize)
ax1.set_title('Rot MNIST', fontsize=fontsize)
ax1.axvline(x=10, ls='--', color='purple', label='ERM: Perfect Train Acc')
ax1.axvline(x=8, ls='--', color='red', label='MatchDG: Perfect Train Acc')


base_dir='results/fashion_mnist/plots/'
legend_arr_mnist=[]
for case in ['ERM', 'MatchDG']:    
    if case == 'MatchDG':    
        file= base_dir + 'matchdg.txt'
    elif case == 'ERM':
        file= base_dir + 'erm.txt'
    
    count=0
    y=[]
    f=open(file ,'r')
    data= f.readlines()
    for line in data:
        if 'Train Loss Basic' in line:
            y.append( float( line.split(':')[-1].split(' ')[-1].rstrip('\n') ) / (5*625) ) 
            count+=1
            if count == 25:
                break
    
    ax2.plot(range(1, 1+len(y)), y, label=case)
    
ax2.set_xlabel('Training Epochs', fontsize=fontsize)
#ax2.set_ylabel('MatchDG Loss Penalty', fontsize=fontsize)
ax2.set_title('Fashion MNIST', fontsize=fontsize)
ax2.axvline(x=19, ls='--', color='purple', label='ERM: Perfect Train Acc')
ax2.axvline(x=15, ls='--', color='red', label='MatchDG: Perfect Train Acc')

lines, labels = fig.axes[-1].get_legend_handles_labels()    
lgd= fig.legend(lines, labels, loc="lower center", bbox_to_anchor=(0.5, -0.3), fontsize=fontsize, ncol=2)
plt.savefig('results/matchdg_plot.jpg', bbox_extra_artists=(lgd,), bbox_inches='tight', dpi=300)

In [ ]:
base_dir='results/rot_mnist/plots/'
for case in ['ERM', 'MatchDG']:    
    if case == 'MatchDG':    
        file= base_dir + 'matchdg.txt'
    elif case == 'ERM':
        file= base_dir + 'erm.txt'
    
    count=0
    y=[]
    f=open(file ,'r')
    data= f.readlines()
    for line in data:
        if 'Train Loss Basic' in line:
            y.append( float( line.split(':')[-1].split(' ')[-1].rstrip('\n') ) ) 
            count+=1
            if count == 25:
                break
    
    plt.plot(range(1, 1+len(y)), y, label=case)
#     print(y)
plt.xlabel('Epochs')
plt.ylabel('Match Function Penalty')
plt.axvline(x=10, ls='--', color='purple', label='ERM: Perfect Train Acc')
plt.axvline(x=8, ls='--', color='red', label='MatchDG: Perfect Train Acc')
# plt.axvline(x=19, ls='--', color='purple', label='ERM: Perfect Train Acc')
# plt.axvline(x=15, ls='--', color='red', label='MatchDG: Perfect Train Acc')
plt.title('Rot MNIST: Match Function Penalty during training process')
plt.legend()
plt.savefig(base_dir + 'matchdg_plot.jpg')
plt.show()

## Eval Acc MNIST (Table 1)

In [ ]:
import numpy as np

In [ ]:
base_path= "results/fashion_mnist/erm_match/logit_match/train_['15', '30', '45', '60', '75']"
for idx in range(3):
    
    file= base_path + "/Val_Acc_0.1_1.0_1.0_5_0_" + str(idx) +"_l2_resnet18.npy"
    arr= np.load(file)        
    print(arr.shape)
    index= np.argmax(arr)
    
    file= base_path + "/Test_Acc_0.1_1.0_1.0_5_0_" + str(idx) +"_l2_resnet18.npy"
    arr= np.load(file)            
    print(arr.shape)
    acc[idx]= arr[index]
    
print('Mean: ', np.mean(acc), ' Std :', np.std(acc))

In [ ]:
arr=[0, 1]
np.pad(arr, (10, 10),'edge')

# Misc

In [ ]:
import torch
loss = torch.nn.CrossEntropyLoss(reduction='none')
input_ = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input_, target)

In [ ]:
output

In [ ]:
    type(np.random.randint(1, 10, 2)[0].item())

In [ ]:
x={'a':2, 'b': 3, 'd':4}
max(x.values())

## Slab Dataset

In [ ]:
#Common imports
import os
import sys
import numpy as np
import argparse
import copy
import random
import json
import pickle

#Pytorch
import torch
from torch.autograd import grad
from torch import nn, optim
from torch.nn import functional as F
from torchvision import datasets, transforms
from torchvision.utils import save_image
from torch.autograd import Variable
import torch.utils.data as data_utils

#Sklearn
from sklearn.manifold import TSNE

#robustdg
from utils.helper import *
from utils.match_function import *

#slab
from utils.slab_data import *
import utils.scripts.utils  as slab_utils
import utils.scripts.lms_utils as slab_lms_utils

In [ ]:
data_1, temp1, _, _= get_data(1000, 0.0, 0.1, 7, 'train', 0, 0)
data_2, temp1, _, _= get_data(1000, 0.1, 0.1, 7, 'train', 0, 0)
data_3, temp1, _, _= get_data(1000, 1.0, 0.1, 7,  'test', 0, 0)

In [ ]:
fig, (ax_1, ax_2, ax_3) = plt.subplots(1,3,figsize=(17, 5))

W = data_1['W']
X, Y = data_1['X'], data_1['Y']
X = X.numpy().dot(W.T)
ax_1.scatter(X[:,0], X[:,1], c=Y, cmap='coolwarm', s=4, alpha=0.8) 
ax_1.set_xlabel('Linear Feature (x1)', fontsize=20)
ax_1.set_ylabel('Slab Feature (x2)', fontsize=20)
ax_1.set_title('Source Domain 1', fontsize=20)

W = data_2['W']
X, Y = data_2['X'], data_2['Y']
X = X.numpy().dot(W.T)
ax_2.scatter(X[:,0], X[:,1], c=Y, cmap='coolwarm', s=4, alpha=0.8) 
ax_2.set_xlabel('Linear Feature (x1)', fontsize=20)
ax_2.set_ylabel('Slab Feature (x2)', fontsize=20)
ax_2.set_title('Source Domain 2', fontsize=20)

W = data_3['W']
X, Y = data_3['X'], data_3['Y']
X = X.numpy().dot(W.T)
ax_3.scatter(X[:,0], X[:,1], c=Y, cmap='coolwarm', s=4, alpha=0.8) 
ax_3.set_xlabel('Linear Feature (x1)', fontsize=20)
ax_3.set_ylabel('Slab Feature (x2)', fontsize=20)
ax_3.set_title('Target Domain', fontsize=20)

plt.tight_layout()
plt.savefig('results/slab_dataset.jpg')

In [ ]:
a= np.ones(2,3)

In [ ]:
import torch
torch.randint(0, 1, (5, 1))

In [ ]:
import random
l=[[0, 1], [2, 3], [9, 8], [0, 2]]
random.shuffle(l)
print(l)

In [ ]:
import numpy as np
x=np.array([1, 2, 3])
y=x

In [ ]:
x[0]= 10
print(x, y)

In [ ]:
import torch 
import copy
a= torch.tensor([1, 2])
b= copy.deepcopy(a)

In [ ]:
a[0]=3
print(a, b)

In [ ]:
a=[1, 2, 3, 5, 6]

In [ ]:
random.choice(a)

In [ ]:
a=torch.tensor([7, 9, 3, 6, 8, 4, 9])
b, c= torch.sort(a)

In [ ]:
print(b)
print(c)

In [ ]:
torch.argmin(a)

In [ ]:
a[c[:3]]

In [ ]:
(a ==9).nonzero()

In [ ]:
a=torch.rand(2,3,4)
b= a.flatten(start_dim=0, end_dim=1)
print(a.shape, b.shape)

c= torch.stack(torch.split(b, a.shape[1]))

print(a==c)

In [ ]:
a

In [ ]:
b

In [ ]:
c

In [ ]:
import numpy as np
n= np.array(range(1, 100))
c1= 181 
c2= -180
c3= -40
c4= -4
x= c1*(n**np.log2(5)) + c2*(n**2)+ c3*(np.log2(n))*(n**2) + c4*((np.log2(n))**2)*(n**2)

In [ ]:
x

In [ ]:
181*np.log2(5) - 448

In [ ]:
5*109+64*9

In [ ]:
n= np.array(range(1, 1000))
y= 181*np.log2(5)*(n**(np.log2(5)-1)) -400*n - 88*(n)*(np.log2(n)) - 8*n*(np.log2(n)**2)

In [ ]:
print(y)

In [ ]:
181*np.log2(5)*(2**(np.log2(5)-1))

In [ ]:
np.log(n)

In [ ]:
n= np.array(range(1, 100))
z= 10*n**(np.log2(5)) - (n**2)*(np.log2(n))

In [ ]:
z

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
n=[1/100*np.array(range(1, 10))]
print(np.cos(n))
print(np.sin(n))


In [ ]:
n= np.array(range(1, 10))
a=[]
for item in n:
    a.append( np.math.factorial(item) )
a=np.array(a)

a= np.log2(a)
b= 0.5*x*np.log2(n)
print(a >= b)

In [ ]:
plt.scatter(a, b)

In [ ]:
print(a)
print(b)

In [ ]:
n= np.array(range(1, 100))
a= 2**(np.log2(n)**2)
b= n**2
print(a >= b)

In [ ]:
plt.plot(n, a, '--')
plt.plot(n, b, '.')

In [ ]:
n=10
x=np.array(range(1, n+1))
f=[]
for item in x:
    f.append(item*(n+1-item))
f=np.array(f)
print(f >= n)

In [ ]:
k=222
n=5023

In [ ]:
s=0
for i in range(k, n+1):
       s+= i
b= 0.5*(n**2 + n - k*(k-1))
print(s, b)

In [ ]:
import torch

In [ ]:
f1='data/datasets/mnist/rot_mnist_lenet/train/seed_0_domain_15_data.pt'
f2='data/datasets/mnist_2/rot_mnist_lenet/train/seed_0_domain_15_data.pt'

a= torch.load(f1)
b= torch.load(f2)

In [ ]:
torch.sum(torch.eq(a, b))/(1000*32*32)

In [36]:
import torch
import torchvision
from torch import nn, optim
        
from opacus.dp_model_inspector import DPModelInspector
from opacus.utils import module_modification

In [3]:
model= torchvision.models.resnet18(1)

In [9]:
model.fc.weight

Parameter containing:
tensor([[-0.0185, -0.0705, -0.0518,  ..., -0.0390,  0.1735, -0.0410],
        [-0.0818, -0.0944,  0.0174,  ...,  0.2028, -0.0248,  0.0372],
        [-0.0332, -0.0566, -0.0242,  ..., -0.0344, -0.0227,  0.0197],
        ...,
        [-0.0103,  0.0033, -0.0359,  ..., -0.0279, -0.0115,  0.0128],
        [-0.0359, -0.0353, -0.0296,  ..., -0.0330, -0.0110, -0.0513],
        [ 0.0021, -0.0248, -0.0829,  ...,  0.0417, -0.0500,  0.0663]],
       requires_grad=True)

In [31]:
class GroupNorm(torch.nn.GroupNorm):
    def __init__(self, num_channels, num_groups=32, **kwargs):
        super().__init__(num_groups, num_channels, **kwargs)

In [32]:
model= torchvision.models.resnet18(0, norm_layer=GroupNorm)

In [35]:
opt= optim.SGD([ {'params': filter(lambda p: p.requires_grad, model.parameters()) }, 
                ], lr= 0.001, weight_decay= 0.0005, momentum= 0.9,  nesterov=True )

In [41]:
model.fc

Linear(in_features=512, out_features=1000, bias=True)

In [86]:
import torch

In [87]:
a=torch.rand(3)

In [88]:
b=a
c=a.clone().detach()

In [89]:
print(a)
print(b)
print(c)

tensor([0.7193, 0.8302, 0.5062])
tensor([0.7193, 0.8302, 0.5062])
tensor([0.7193, 0.8302, 0.5062])


In [90]:
b[2]=-10
b[1]=-10

In [91]:
print(a)
print(b)
print(c)

tensor([  0.7193, -10.0000, -10.0000])
tensor([  0.7193, -10.0000, -10.0000])
tensor([0.7193, 0.8302, 0.5062])


In [93]:
(b == -10).nonzero()[1,0]

tensor(2)